spring:
  application:
    name: Kotlin Spring Boot Sample Project
  resources:
    add-mappings: false
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    deserialization.FAIL_ON_UNKNOWN_PROPERTIES: true
server:
  port: 8080